// The initial version of this file has been generated by TS by running
//    tools::package_native_routine_registration_skeleton('.',,,FALSE);
// within the package repository root.
//
// You can re-generate this file with the same command after adding
// new C++ functions or edit it by hand.

#include <R.h>
#include <Rinternals.h>
#include <stdlib.h> // for NULL
#include <R_ext/Rdynload.h>


/* .Call calls */
extern SEXP smooth_data(SEXP, SEXP, SEXP);
extern SEXP interp_tris_c(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
  {"smooth_data", (DL_FUNC) &smooth_data, 3},
  {"interp_tris_c", (DL_FUNC) &interp_tris_c, 5},
  {NULL, NULL, 0}
};

void R_init_haze(DllInfo *dll)
{
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}

